GtRacingNews/Controllers/AllController.cs
using GtRacingNews.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GtRacingNews.Controllers
{
    public class AllController : Controller
    {
        private readonly IEngine engine;
        public AllController(IEngine engine) => this.engine = engine;

        public async Task<IActionResult> AllChampionships() => View(engine.returnAll.All("Championships"));
        public async Task<IActionResult> AllDrivers() => View(engine.returnAll.All("Drivers"));
        public async Task<IActionResult> AllNews() => View(engine.returnAll.All("News"));
        public async Task<IActionResult> NewsDetails(string Id) => View(engine.returnAll.NewsDeatils(Id));
        public async Task<IActionResult> AllRaces() => View(engine.returnAll.All("Races"));
        public async Task<IActionResult> AllTeams() => View(engine.returnAll.All("Teams"));
    }
}

GtRacingNews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GtRacingNews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GtRacingNews.styles.css" asp-append-version="true" />
</head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-dark bg-dark border-bottom box-shadow mb-3">

            @*side bar menu toggle button*@
            <div id="main">
                <button id="openNav" style="margin-right: 25px;" class="w3-button w3-teal w3-xmedium" onclick="w3_open()">&#9776;</button>
            </div>
            @*side bar menu toggle button*@

            <h1 class="navbar-brand">Welcome @this.User.Identity.Name</h1>

            <ul class="navbar-nav" style="float: none; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">

                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="All" asp-action="AllNews">NEWS</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="All" asp-action="AllTeams">TEAMS</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="All" asp-action="AllChampionships">CHAMPIONSHIPS</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="All" asp-action="AllDrivers">DRIVERS</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="All" asp-action="AllRaces">RACING CALENDAR</a>
                </li>

            </ul>

        </nav>

        @*side bar menu*@
        <div class="w3-sidebar w3-bar-block w3-card w3-animate-left navbar-dark bg-dark" style="display:none" id="mySidebar">
            <button class="w3-bar-item w3-button w3-large nav-link text-light"
                    onclick="w3_close()">
                Close &times;
            </button>

            @if (!this.User.IsInRole("Moderator") && !this.User.IsInRole("Admin") && !this.User.Identity.IsAuthenticated)
            {
                <a href="/User/Register" class="w3-bar-item w3-button nav-link text-light">Register</a>
                <a href="/User/LogIn" class="w3-bar-item w3-button nav-link text-light">Log In</a>
            }

            @if (!this.User.IsInRole("Moderator") && !this.User.IsInRole("Admin") && this.User.Identity.IsAuthenticated)
            {
                <a href="/User/Profile" class="w3-bar-item w3-button nav-link text-light">Become Premium Member</a>
            }

            @if (this.User.Identity.IsAuthenticated)
            {
                <a href="/User/Logout" class="w3-bar-item w3-button nav-link text-light">Logout</a>
            }
            @if (this.User.IsInRole("Moderator") && this.User.Identity.IsAuthenticated)
            {
                <a href="/Profile/MyProfile" class="w3-bar-item w3-button nav-link text-light">My Profile</a>
            }
            @if (this.User.IsInRole("Moderator"))
            {
                <a href="/Premium/Add/AddTeam" class="w3-bar-item w3-button nav-link text-light">Add Team</a>
                <a href="/Premium/Add/AddNews" class="w3-bar-item w3-button nav-link text-light">Add News</a>
                <a href="/Premium/Add/AddRace" class="w3-bar-item w3-button nav-link text-light">Add Race</a>
                <a href="/Premium/Add/AddDriver" class="w3-bar-item w3-button nav-link text-light">Add Driver</a>
                <a href="/Premium/Add/AddChampionship" class="w3-bar-item w3-button nav-link text-light">Add Championship</a>
            }
        </div>
        @*side bar menu*@

    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/OpenSideMenu.js"></script>
    <script src="~/js/CloseSideMenu.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>